In [ ]:
# NUMPY : NUmerical Python

In [2]:
import  numpy as np


In [9]:
list1 = ['Artificial Intelligence',1,3.5,10]
print(type(list1))

<class 'list'>


In [8]:
np.array(list)

array(<class 'list'>, dtype=object)

In [10]:
type(np.array(list))

numpy.ndarray

In [12]:
np.array([5,6,7,8,9.]) # it will convert all element to float because float is higher than int

array([5., 6., 7., 8., 9.])

In [15]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [16]:
np.array([[1,2],[3,4]]).ndim

2

In [17]:
np.array([[[1,2],[3,4]]]).ndim

3

In [18]:
a=np.array([[1,2],[3,4]])

In [19]:
a[1][1]

4

In [22]:
#convert 1 d array to 2d
d2= np.array([1,2,3,4],dtype = 'float',ndmin = 2)

array([[1., 2., 3., 4.]])

In [3]:
d3=np.array([1,2,3,4],dtype = 'float',ndmin = 3)

array([[[1., 2., 3., 4.]]])

In [4]:
d3=np.array([1,2,3,4],dtype = 'float',ndmin = 3).shape

(1, 1, 4)

In [6]:
d4= np.array([1,2,3,4],dtype = 'float',ndmin = 4)

In [7]:
d4.shape

(1, 1, 1, 4)

In [8]:
d4

array([[[[1., 2., 3., 4.]]]])

In [9]:
print(d4)

[[[[1. 2. 3. 4.]]]]


In [19]:
d4= np.array([[[2,3,4],[3,4,5]],[[4,5,6],[7,8,9]]],dtype = 'float',ndmin = 4)
print(d4)

[[[[2. 3. 4.]
   [3. 4. 5.]
   [4. 5. 6.]
   [7. 8. 9.]]]]


In [20]:
# (1,1,2,3) (configuration,matrix count,Rows,columns)
d4.shape

(1, 1, 4, 3)

# Matrices


In [21]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [23]:
np.mat([1,2,3,4,5,6]) #matrix cannot be 1d, but array can be 1d

matrix([[1, 2, 3, 4, 5, 6]])

In [24]:
list1 = [1,2,3,4,5]

In [25]:
np.asarray(list1)

array([1, 2, 3, 4, 5])

In [27]:
np.mat(list1)

matrix([[1, 2, 3, 4, 5]])

In [28]:
np.asanyarray(list1)

array([1, 2, 3, 4, 5])

In [30]:
np.asanyarray(np.mat(list1))

matrix([[1, 2, 3, 4, 5]])

In [31]:
#to find difference between asarray and asanyarray

# Create an array from function

In [32]:
np.fromfunction(lambda i,j : 1==j,(4,4))

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False],
       [False,  True, False, False]])

In [33]:
np.fromfunction(lambda i,j : i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [34]:
np.fromfunction(lambda i,j : i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [37]:
np.fromfunction(lambda i,j : i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [38]:
np.fromfunction(lambda i,j,k : i*j*k,(4,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 1.],
        [0., 2.],
        [0., 3.]],

       [[0., 0.],
        [0., 2.],
        [0., 4.],
        [0., 6.]],

       [[0., 0.],
        [0., 3.],
        [0., 6.],
        [0., 9.]]])

In [43]:
np.fromfunction(lambda i,j,k,l : i*j*k*l,(4,4,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 1.]],

        [[0., 0.],
         [0., 2.]],

        [[0., 0.],
         [0., 3.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 2.]],

        [[0., 0.],
         [0., 4.]],

        [[0., 0.],
         [0., 6.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 3.]],

        [[0., 0.],
         [0., 6.]],

        [[0., 0.],
         [0., 9.]]]])

# Convert array into dataframe

In [47]:
import pandas as pd
a=np.fromfunction(lambda i,j: i*j,(400,400), dtype=int)
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9    ...     390  \
0      0    0    0     0     0     0     0     0     0     0  ...       0   
1      0    1    2     3     4     5     6     7     8     9  ...     390   
2      0    2    4     6     8    10    12    14    16    18  ...     780   
3      0    3    6     9    12    15    18    21    24    27  ...    1170   
4      0    4    8    12    16    20    24    28    32    36  ...    1560   
..   ...  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...     ...   
395    0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  154050   
396    0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  154440   
397    0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  154830   
398    0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  155220   
399    0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  155610   

        391     392     393     394     395     396     397     398     399  
0         0       0       0       0       0       0       0       0       0  
1       391     392     393     394     395     396     397     398     399  
2       782     784     786     788     790     792     794     796     798  
3      1173    1176    1179    1182    1185    1188    1191    1194    1197  
4      1564    1568    1572    1576    1580    1584    1588    1592    1596  
..      ...     ...     ...     ...     ...     ...     ...     ...     ...  
395  154445  154840  155235  155630  156025  156420  156815  157210  157605  
396  154836  155232  155628  156024  156420  156816  157212  157608  158004  
397  155227  155624  156021  156418  156815  157212  157609  158006  158403  
398  155618  156016  156414  156812  157210  157608  158006  158404  158802  
399  156009  156408  156807  157206  157605  158004  158403  158802  159201  

[400 rows x 400 columns]